# Generated by Django 2.1.3 on 2018-11-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='weight',
        ),
        migrations.AddField(
            model_name='measurement',
            name='current_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='goal_weight',
            field=models.FloatField(default=0),
        ),
    ]
